### ISSUE TITLE
Pipeline error with test data related to metrics.py

### ISSUE THREAD

**Issue by anikaliu** [theislab/scib-pipeline#10]
Hello,
I'm having trouble running the pipeline with the test and it seems to get stuck at the rule `metrics_single `which executes 
`conda run -n scIB-python python scripts/metrics/metrics.py -u data/adata_norm.h5ad -i /data/al862/scib_pipeline/data/test_data/integration/unscaled/full_feature/scanorama.h5ad          -o /data/al862/scib_pipeline/data/test_data/metrics/unscaled/full_feature/scanorama_full.csv -m scanorama          -b batch -l celltype --type full          --hvgs 0 --organism mouse --assay expression -v`

I've attached the progress/error messages below, any help with this would be much appreciated!
Best wishes,
Anika
```
Options
    type:       full
    batch_key:  batch
    label_key:  celltype
    assay:      expression
    organism:   mouse
    n_hvgs:     None
    setup:      scanorama_full
    optimised clustering results:       /data/al862/scib_pipeline/data/test_data/metrics/unscaled/full_feature/scanorama_full_nmi.txt
reading adata before integration
AnnData object with n_obs × n_vars = 2730 × 3451
    obs: 'paul15_clusters', 'celltype', 'batch', 'n_counts'
    var: 'n_counts'
    uns: 'iroot'
    layers: 'counts'
reading adata after integration
AnnData object with n_obs × n_vars = 2730 × 3451
    obs: 'paul15_clusters', 'celltype', 'batch', 'n_counts'
    var: 'n_counts'
    obsm: 'X_emb', 'X_scanorama'
reduce integrated data:
    HVG selection:      None
    compute neighbourhood graph:        True on X_pca
    precompute PCA:     True
PCA
Nearest Neigbours
computing metrics
type:   full
    ASW:        True
    NMI:        True
    ARI:        True
    PCR:        True
    cell cycle: True
    iso lab F1: True
    iso lab ASW:        True
    HVGs:       True
    kBET:       True
    LISI:       True
    Trajectory: False
clustering...
optimised clustering against celltype
optimal cluster resolution: 1.5
optimal score: 0.47700604961660414
saved clustering NMI values to /data/al862/scib_pipeline/data/test_data/metrics/unscaled/full_feature/scanorama_full_nmi.txt
NMI...
ARI...
silhouette score...
PC regression...
covariate: batch
compute PCA n_comps: 50
covariate: batch
compute PCA n_comps: 50
cell cycle effect...

/home/al862/anaconda3/envs/scIB-python/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:14: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 248, in <module>
    trajectory_=trajectory_
  File "/home/al862/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scIB/metrics.py", line 1865, in metrics
    agg_func=np.mean, organism=organism)
  File "/home/al862/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scIB/metrics.py", line 582, in cell_cycle
    raise ValueError(message)
ValueError: batch "3" of batch_key "batch" has unequal number of entries before and after integration.before: 564 after: 550
```

**Comment by LuckyMD** [comment]
Hi @anikaliu,

Sorry for the delayed reply here. This looks like something we have encountered before and should work. Could I ask which version of scanorama you are running? It seems that you have more cells after integration than before. 

Have you compared the `/data/al862/scib_pipeline/data/test_data/integration/unscaled/full_feature/scanorama.h5ad` output to your input data file? Are there any cells that seem to be duplicated? Or is it the case the we have 0 expression cells in the test object. 

@mumichae this shouldn't have to do with the test object, no?

**Comment by mumichae** [comment]
Also, which version of scanorama are you using?

**Comment by anikaliu** [comment]
Hi @LuckyMD,
thanks for your reply! I hadn't checked any of the things you mentioned but have done it now:

- The scanorama version is 1.7 (through bioconda). 
- The number of cells per batch is identical in the input and output h5ad (also for `adata_output.obsm['X_scanorama'] `)
- There aren't any cells without expressed genes in the input object

Please let me know if there's anything else I can check or send over to sort this out!:)

**Comment by LuckyMD** [comment]
Hmm... and the `adata.obs['batch']` before and after integration are exactly the same?

**Comment by mumichae** [comment]
There only time we encountered this error was when `scanorama` overwrote the batch column in `adata.obs`, which should have been fixed in version 1.7. Are you checking the version in the `scIB-python` environment?

Another thing you could try is switching to the [update_scanpy](https://github.com/theislab/scib-pipeline/tree/update_scanpy) branch and setting up the environments `scib-pipeline` and `scib-R`. The dependencies there should be more up-to-date.

**Comment by anikaliu** [comment]
I've re-run after deleting the intermediate files now and noticed that actually the batches are mixed up! I hadn't noticed it because the frequencies were the same. I've now checked that the same samples are still in the same batch, so it's only the batch IDs are somehow different.. does this information help somehow?

**Comment by mumichae** [comment]
Yes, it sounds very much like a bug that was in an older scanorama version. In the unintegrated adata  object (`adata_norm.h5ad`) what data type does the batch column have? It should be categorical or String, but not integer.

Could you also confirm that you are checking the scanorama versions in the `scIB-python` environment (or `scib-pipeline` environment, if working on #6 ) and/or whether you're running the pipeline from this environment?  The integration methods are explicitly run in this conda environment.

Assuming that you're working with the same data and environments as described in the repo, we should be getting the same behaviour (scanorama works for me).

**Comment by mumichae** [comment]
@anikaliu Did you resolve your issue or are you still getting mixed-up batches with scanorama 1.7?

**Comment by anikaliu** [comment]
Really sorry for not getting back to you! I haven't been able to sort it but also haven't tried it with the update_scanpy branch yet. I will be trying what you suggested, but it might take me a while to get to it. (Totally understand if you prefer to close the issue for now)
