### ISSUE TITLE
data sets available?

### ISSUE THREAD

**Issue by zia1138** [theislab/scib-pipeline#11]
Great job on the scib pipeline. I imagine it was a big headache getting all of these methods to work. I was wondering if the benchmark data set h5ad files were available for download? They seem to be hard coded in config/reproduce_paper.yaml  Thanks!

**Comment by LuckyMD** [comment]
Hi @zia1138,

The data are all on the figshare here: https://figshare.com/articles/dataset/Benchmarking_atlas-level_data_integration_in_single-cell_genomics_-_integration_task_datasets_Immune_and_pancreas_/12420968

This is in the revised manuscript... that should be out soon I hope :). We should probably also add this to the README... @mumichae could you add the link?

**Comment by zia1138** [comment]
No hurry on my end.  Thank you again for the great work. It's nice to see a careful evaluation of all of these approaches.

**Comment by LuckyMD** [comment]
Thanks :).
