### ISSUE TITLE
Installation issues that need fixing

### ISSUE THREAD

**Issue by LuckyMD** [theislab/scib-pipeline#23]
Things to improve installation experience:
* [x] pin rpy2 3.4.2
  * install specifically via conda (if possible)
* [x] scib: try-except around ro.r('library(Seurat)’) to report that library installs were problematic
* README:
  * [x] Add “This is a 3-5 step installation” to give overview of long installation section-> add links to sections
  * [x] remove details, improve flow
  * [x] First have small statements of simple instructions, then go deeper to details

**Comment by LuckyMD** [comment]
@mumichae I will take a look at the README, maybe you could take a look at the first 2 steps

**Comment by Hrovatin** [comment]
@mumichae 
The below also causes issue for me:
```
(base) [karin.hrovatin@icb-lisa scib-pipeline]$ pwd
/storage/groups/ml01/code/karin.hrovatin/scib-pipeline
(base) [karin.hrovatin@icb-lisa scib-pipeline]$ . envs/set_vars.sh $HOME/miniconda3/envs/scib-pipeline
dirname: invalid option -- 'b'
Try 'dirname --help' for more information.
cp activate_env_vars.sh /home/icb/karin.hrovatin/miniconda3/envs/scib-pipeline/etc/conda/activate.d/env_vars.sh
cp: cannot stat '/env_vars_activate.sh': No such file or directory
cp deactivate_env_vars.sh /home/icb/karin.hrovatin/miniconda3/envs/scib-pipeline/etc/conda/deactivate.d/env_vars.sh
cp: cannot stat '/env_vars_deactivate.sh': No such file or directory

**Comment by mumichae** [comment]
@Hrovatin Are you using shell or bash? Maybe try with
```
bash envs/set_vars.sh $HOME/miniconda3/envs/scib-pipeline
```

**Comment by Hrovatin** [comment]
That worked, thanks.

**Comment by mumichae** [comment]
> 

Which environment is that from?

**Comment by mumichae** [comment]
@LuckyMD I just checked the code and calling Seurat via rpy2 is something that is only done in the scib package. Are points 1 and 2 also something you want reflected in the scib package?

**Comment by LuckyMD** [comment]
Yes, i think that would be useful.

**Comment by mumichae** [comment]
rpy2 library loading checking is addressed in `scib` and all other suggestions have been applied in #20
