### ISSUE TITLE
Solving env with conda causes memory usage explosion

### ISSUE THREAD

**Issue by szymczakpau** [theislab/scib-pipeline#24]
Hi!

I tried setting up _scib-pipeline_ with conda and solving env causes OOM on my 32G RAM machine. 

![image](https://user-images.githubusercontent.com/47643690/161258216-dc1c051a-aa3e-46b1-ae6c-07da5555e819.png)

Is this something that you have experienced? 
I am currently trying to run this on machine with 125G RAM, but it takes a really long time (more than 1 hr as of now).

**Comment by mumichae** [comment]
Hi, try using mamba, it should be a lot more time and memory efficient.
https://mamba.readthedocs.io/en/latest/installation.html 

i.e. after installing mamba into the conda base environment, run
```
mamba env create -f envs/scib-pipeline.yml
```

**Comment by szymczakpau** [comment]
It works! I saw your note in README on speeding up time with mamba, but didn't know it also affect memory performance! Thanks!
