### ISSUE TITLE
Setting environnement variables

### ISSUE THREAD

**Issue by t-nol** [theislab/scib-pipeline#33]
Hi, 
I'd like to start by saying I am relatively new to bioinformatics and might just be missing something obvious, thank you for your patience. 

1. I'd like to run this pipeline  but i can't seem to install the additionnal R packages needed. I've set the environment variables manually as was written in the ReadMe : 

```console
conda activate scib-pipeline
echo $CONDA_PREFIX  # referred to as <conda_prefix>
conda deactivate

cp envs/env_vars_activate.sh <conda_prefix>/etc/conda/activate.d/env_vars.sh
cp envs/env_vars_deactivate.sh <conda_prefix>/etc/conda/deactivate.d/env_vars.sh
```

But when i try to install packages i get the following message : 

```console
conda activate scib-R4
cd envs/
Rscript install_R_methods.R r4_dependencies.tsv
R dependencies from r4_dependencies.tsv
Dependencies:
                    package version    how
1:      kharchenkolab/conos   1.3.0 github
2: kharchenkolab/conosPanel    <NA> github
3:                  harmony    <NA>   cran
install kharchenkolab/conos
install kharchenkolab/conos@v1.3.0 from Github
Erreur : .onLoad a échoué dans loadNamespace() pour 'pkgload', détails :
  appel : NULL
  erreur : package ‘rprojroot’ was installed before R 4.0.0: please re-install it
Exécution arrêtée
```

2. I've checked in both python and R environment and .libPaths() doesn't seem to be changed to the conda environment R library, is this related to my problem ?

Thank you for your help!

**Comment by mumichae** [comment]
Hi @t-nol ,

That's correct, the .libPaths() needs to be the conda path in order to work with the conda environment. Just to make sure, are you replacing `<conda-prefix>` with your actual environment path? And do you get any errors when you set the environment variables or activate/deactivate the environments?

**Comment by t-nol** [comment]
@mumichae 
Yes I did replace `<conda-prefix>` by the environment path. Both `activate.d/env_vars.sh` and `deactivate.d/env_vars.sh` files exist and contain the same code as `env_vars_*.sh` files provided in the `envs/` directory.
No i haven't seen any errors while activating/deactivating the environments.

**Comment by mumichae** [comment]
Sorry for the late reply. I updated the repository to include a single-command installation script and renamed the environment names. If you're still setting up the environments, I switch to the latest update.

To your issue: could you also double-check which R instance you're using (I assume you also have a system-wide R installation that might be competing with the conda installation)

e.g.
```
conda activate scib-R4
which R
```

**Comment by t-nol** [comment]
No problem, thank you for taking the time. 

I've been busy myself and haven't managed to set up the environments. There is a system wide version of R installed so this might be it. 
I will try using the updated version, in the meantime here is what i get for the scib-R4 env : 
```
conda activate scib-R4
which R
/CONDAS/users/tnoel/scib-R4/bin/R
```

**Comment by t-nol** [comment]
So.. I've tried installing the updated version with the single-command installation script. Both environnement were created but I still get this error after : 
```
Install R packages through R
scib pipeline environment...
Erreur : Failed to install 'kBET' from GitHub:
  package ‘rprojroot’ was installed before R 4.0.0: please re-install it
Exécution arrêtée
ERROR conda.cli.main_run:execute(41): `conda run Rscript -e remotes::install_github('theislab/kBET', quiet=TRUE)` failed. (See above for error)
```

I'm guessing it's still not the right R library that is being used in the conda environments. The cluster I'm working on has the version 3.6.0 of R installed but i tried switching to R version 4.1.1 and still got the same message. Any idea what could cause this ?

**Comment by mumichae** [comment]
Yes, I think it's still the same issue. Could you check any variables that R uses, such as R_HOME etc.?

**Comment by t-nol** [comment]
Here's what i tried : 
- in the scib-R4.0 environment :
```
conda activate scib-R4.0
echo $R_HOME
/CONDAS/users/tnoel/scib-R4.0/lib/R
echo $R_LIBS

echo $R_LIBS_SITE

echo $R_LIBS_USER

```

- in the scib-pipeline-R4.0 env : 
```
conda activate scib-pipeline-R4.0
echo $R_HOME
/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/R
echo $R_LIBS

echo $R_LIBS_SITE

echo $R_LIBS_USER

```

R_LIBS and a few others do not seem to be defined. I am not very familiar with the way R works so if there are any others you'd want me to check please let me know.

**Comment by t-nol** [comment]
Hi. I've found the origin of my problem. I had an old .Rprofile file in my home directory which directed the $R_LIBS to the wrong library. I don't know why i didn't try this first but i realised it after using `.libPaths()` in R in the scib-R4.0 environment and seeing that the conda R library i wanted was in 2nd position. After removing this file from my home directory i was able to set the environments up with out any troubles. 
Sorry I haven't thought of checking this before. Thank you so much for taking the time to help me!
