### ISSUE TITLE
Error when running snakemake

### ISSUE THREAD

**Issue by t-nol** [theislab/scib-pipeline#34]
Hi. As with my precedent issue, this is probably an error linked to the system I work on but I am hoping someone will have an idea as to why this is happening. 

I have set up the R4.0 environments and wanted to run it on the test data generated with the `generate_data.py` script provided in the data directory. The dry run `snakemake --configfile configs/test_data-R4.0.yaml -n --use-conda` works fine but i get the following error after `snakemake --configfile configs/test_data-R4.0.yaml --cores 10 --use-conda`  :

```
ERROR conda.cli.main_run:execute(41): `conda run python scripts/preprocessing/runPP.py -i data/adata_norm.h5ad -o /SCRATCH-BIRD/users/tnoel/atlas/tools/scib-pipeline/data/test_data_r4/prepare/unscaled/full_feature/adata_pre.RDS -b batch --hvgs 0 -r -l` failed. (See above for error)
Save as RDS

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 51, in runPP
    scib.preprocessing.saveSeurat(adata, outPath, batch, hvgs)
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/_package_tools.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 707, in save_seurat
    ro.r('sobj = as.Seurat(adata, counts="counts", data = "X")')
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 438, in __call__
    res = self.eval(p)
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/CONDAS/users/tnoel/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in as.Seurat(adata, counts = "counts", data = "X") : 
 cannot find function "as.Seurat"


[Thu May 12 16:31:59 2022]
Error in rule integration_prepare:
    jobid: 10
    output: /SCRATCH-BIRD/users/tnoel/atlas/tools/scib-pipeline/data/test_data_r4/prepare/unscaled/full_feature/adata_pre.RDS
    shell:
        
        conda run -n scib-pipeline-R4.0 python scripts/preprocessing/runPP.py -i data/adata_norm.h5ad         -o /SCRATCH-BIRD/users/tnoel/atlas/tools/scib-pipeline/data/test_data_r4/prepare/unscaled/full_feature/adata_pre.RDS -b batch         --hvgs 0  -r -l
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I'm also getting a lot of warnings but I am not sure this would be linked to my problem seeing as most of them are about deprecated names. 

Has anyone encountered this kind of issue ? I've checked and am able to use the as.Seurat function in R from both R4.0 environments.

**Comment by mumichae** [comment]
Hi, it seems as though Seurat is not installed. Have you tried rerunning the installation script again? That should update the environments after failed tries.

Btw, `--use-conda` should not be necessary, since the pipeline doesn't create conda environments from the yaml files, but instead uses the pre-installed conda environments. This is mainly due to rpy2 and wrong library path issues.

**Comment by t-nol** [comment]
I thought as much but i couldn't launch the script without adding `--use-conda`. I'll try rerunning the installation script.

**Comment by t-nol** [comment]
So, rerunning the script did not help. It basically tells me that all required packages are already installed (for both conda and pip installed packages).
Here is what happens when i try launching the script from the scib-pipeline-R4.0 env : 
```
$ snakemake --configfile configs/test_data-R4.0.yaml -n
Error: --use-conda must be set if --conda-prefix or --create-envs-only is set.
```
However when I open R from this same environment and look at the .libPaths() : 
```
> .libPaths()
[1] "~/scib-pipeline-R4.0/lib/R/library"
```
I have no idea why this is happening..

**Comment by mumichae** [comment]
The .libPaths looks fine. Not quite sure why the error pops up, seeing that you didn't specify any conda flags on the command. Could you try to see if a minimal example in snakemake works? https://snakemake.readthedocs.io/en/stable/tutorial/short.html

**Comment by t-nol** [comment]
If you're reffering to the ~ at the start of the path i replaced some personal ids with it.  
I'll try that, thank you for your help!

**Comment by t-nol** [comment]
Hi again,
So the need to use the --use-conda flag seems linked to a few variables set by the admin of my system that I was not made aware of. This shouldn't however be responsible for the problems I am meeting with the library paths. I will try and see if I can find out where this is coming from but the admin I have asked doesn't know either what could be causing this.

**Comment by mumichae** [comment]
Regarding the libpaths, it might that the script was having issues detecting the conda prefix path and using $HOME instead. I suggest you [set these variables manually](https://github.com/theislab/scib-pipeline/tree/main/envs#2-setting-environment-variables) for both variables.

**Comment by mumichae** [comment]
Hi, please let me know if you're still facing any issues otherwise we can close this issue.

**Comment by t-nol** [comment]
Hi, sorry for not getting back to you. I didn't find the time to get back to this issue. But seeing as this is clearly linked to the system I am working on i'd say we can close this issue. 
Thank you for your help.
