### ISSUE TITLE
Providing custom variable gene to the full pipeline

### ISSUE THREAD

**Issue by stemangiola** [theislab/scib-pipeline#42]
Hello, I would like to know if there is a way with the current setup to provide custom variable jeans to all algorithms.

Thanks a lot

**Comment by LuckyMD** [comment]
Hi @stemangiola,

We haven't set up the pipeline to be able to do that. What you could however do is fork the `scib` repository and then edit the `hvg_batch` function to always output a pre-defined gene list, see:
https://github.com/theislab/scib/blob/ad40b62d4c8b3a5712ef2bc46853588a2b8cf149/scib/preprocessing.py#L465

Hope that helps!
