### ISSUE TITLE
scvi and other issues?

### ISSUE THREAD

**Issue by AlinaKurjan** [theislab/scib-pipeline#46]
Hi all, thank you for your wonderful work, I am really keen to apply it for my own analysis. Did a fresh install of the pipeline today and had success running it with test data and the small test config pipeline, but unfortunately running into a few issues with my own data.

**First error** concerns the scvi.module not being installed and I am not entirely sure how to install it as I get dependency issues with both pip and mamba. I see that you are already trying to update code to include `scvi-tools` rather than `scvi`. Will this issue be fixed by this change?

**Second error** is this: 
```
Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 51, in runPP
    scib.preprocessing.saveSeurat(adata, outPath, batch, hvgs)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/_package_tools.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 732, in save_seurat
    ro.globalenv["adata"] = adata
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/environments.py", line 34, in __setitem__
    robj = conversion.converter.py2rpy(value)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/py2r.py", line 60, in py2rpy_anndata
    row_args = {k: pandas2ri.py2rpy(v) for k, v in obj.var.items()}
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/py2r.py", line 60, in <dictcomp>
    row_args = {k: pandas2ri.py2rpy(v) for k, v in obj.var.items()}
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py", line 191, in py2rpy_pandasseries
    res = func(obj)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 93, in numpy2rpy
    res = unsignednumpyint_to_rint(o)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 68, in unsignednumpyint_to_rint
    if intarray.itemsize >= (RINT_SIZE / 8):
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'itemsize'

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i [...my long redacted path...]/quads_labelled_scbi.h5ad -o [...my long redacted path...]/devquads/prepare/unscaled/full_feature/adata_pre.RDS -b sample --hvgs 0 -r -l` failed. (See above for error)
```

Any ideas what could be causing this? Thank you again!

**Comment by LuckyMD** [comment]
Hi @AlinaKurjan,

This looks like an issue with saving HVGs to a separate file for a Seurat run rather than anything to do with scvi or scvi-tools. The issue is being caused by the conversion from anndata to SCE via rpy2. You should be getting the same issue if you start a python session in the conda environment you installed and just do the following:

```
import anndata2ri
import scanpy as sc
import rpy2.robjects as ro

anndata2ri.activate()
adata = sc.read('/path/to/your/data')
ro.globalenv["adata"] = adata
```

If the test data runs through fully then, replacing your file name read by:
`adata = sc.datasets.pbmc68k_reduced()`

Should work again. Could you test this?

It seems that your issue is related to an 'uint' data column in your dataset. R doesn't have this data format, so it can't be converted. This is probably in your `adata.obs` or your `adata.var` as it's a pandas series.

Could you print the outputs of `adata.obs.dtypes` and `adata.var.dtypes`? One of the columns you have should say something like "UInt32". That needs to be removed or converted.

**Comment by AlinaKurjan** [comment]
Hi Malte, thank you for a quick reply! 

1) I did get the scvi.modules error, it was just self-explanatory so I didn't include the code for it, apologies for confusion. Here:

```
Traceback (most recent call last):
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/integration.py", line 260, in scanvi
    from scvi.model import SCANVI
ModuleNotFoundError: No module named 'scvi.model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/integration/runIntegration.py", line 67, in <module>
    runIntegration(file, out, run, hvg, batch, celltype)
  File "scripts/integration/runIntegration.py", line 22, in runIntegration
    integrated = method(adata, batch, celltype)
  File "/home/a/akurjan/obds_conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/integration.py", line 262, in scanvi
    raise OptionalDependencyNotInstalled(e)
scib.exceptions.OptionalDependencyNotInstalled: 
scvi.model is an optional dependency and not installed by default. Please make sure you install it manually.
ERROR conda.cli.main_run:execute(49): `conda run python scripts/integration/runIntegration.py -i /t1-data/project/tendonhca/akurjan/SCENIC_dev/cellranger/quads/scib_files/devquads/prepare/unscaled/hvg/a
data_pre.h5ad -o /t1-data/project/tendonhca/akurjan/SCENIC_dev/cellranger/quads/scib_files/devquads/integration/unscaled/hvg/scanvi.h5ad -b sample --method scanvi -v 2000 -c celltype` failed. (See above
 for error)
```
If I try installing it specifically with pip:
```
(scib-pipeline-R4.0) pip install scvi.model
ERROR: Could not find a version that satisfies the requirement scvi.model (from versions: none)
ERROR: No matching distribution found for scvi.model
```
Any tips for this?

I'll have a look at your suggestions for the rest and get back shortly.

**Comment by AlinaKurjan** [comment]
Seems like converting the formats resolves the second error, however the pipeline still fails due to the `scvi.model` not being installed (see above). Could you please advise on the best course of action in this case? Does it mean that the scvi package installation is incomplete? 

Thank you for your help!

**Comment by mumichae** [comment]
Hi @AlinaKurjan, I'm currently looking into this in #45. Do to an update in scvi to scvi-tools the imports have changed. I'll let you know when the issue is resolved

**Comment by LuckyMD** [comment]
On another note... Forgive that I googled you briefly, @AlinaKurjan... but I see you're working on tendon. Are you already building an integrated tendon atlas? or is your use of scib more for sample-level integration? It would be super cool to see an integrated reference atlas also for more difficult tissues to study, like tendon.

**Comment by AlinaKurjan** [comment]
@LuckyMD As a group, we are indeed exploring our options for building an integrated atlas that would span different tendon types, ages, and health states. I am personally working with human developing tendons, which adds a whole other layer of complexity, and unfortunately the more I try to figure out the best way to process and integrate my data, the more questions I am left with. That is also why I think the scib tool would be invaluable in helping us pick the best approach 🙂 I'd be really keen to get a few of your thoughts on our work later on if you would be interested!

For now, I will attempt to run the pipeline without scvi and scanvi and then compare with those two methods applied manually in a separate environment. 

Thank you again for all the help so far.

**Comment by mumichae** [comment]
The pipeline should now be updated to use the newest scvi-tools version. You can update your environments as follows (assuming you have `mamba` installed, otherwise feel free to replace `mamba` with `conda`):

```
git pull

# make sure to remove the old dependency
conda activate scib-pipeline-R4.0
mamba remove scvi 
conda deactivate  # make sure to deactivate before the next step

bash envs/create_conda_environments.sh -r 4.0
```

**Comment by LuckyMD** [comment]
@AlinaKurjan I'd be happy to have a chat about tendon integration if you like. We are just looking to build and write up some guidelines for tissue integration, which may help... but there are always tissue-specific challenges.

Hope scVI and scANVI can now also be compared.

**Comment by AlinaKurjan** [comment]
@LuckyMD @mumichae Thank you for your help so far, I've run the scvi and scanvi now with no issues. One final note is that I did not get any readouts for trajectory with any methods. What could be the reason here?

**Comment by LuckyMD** [comment]
Trajectory requires you to manually annotate (using e.g., sc.tl.dpt) a trajectory per batch that you'd like to check for conservation in the integrated object. If you'd like to do this, you can store the trajectory in a designated `adata.obs` column. I'd need to check the column name again though.

**Comment by AlinaKurjan** [comment]
Thank you! @mumichae mentioned it needs to be  saved as .obs["dpt"]. I'll give that a go. The results are really interesting already, looks like scVI and scANVI are most fitting for my data too :)
