### ISSUE TITLE
No trajectory output

### ISSUE THREAD

**Issue by mumichae** [theislab/scib-pipeline#47]
@LuckyMD @mumichae Thank you for your help so far, I've run the scvi and scanvi now with no issues. One final note is that I did not get any readouts for trajectory with any methods. What could be the reason here? 

_Originally posted by @AlinaKurjan in https://github.com/theislab/scib-pipeline/issues/46#issuecomment-1282009252_

**Comment by mumichae** [comment]
The trajectory score is only computed on cells that are assigned a DPT ordering, which needs to be computed beforehand on the cells of interest. Make sure that the DPT values are saved under .obs["dpt"] for the pipeline

**Comment by AlinaKurjan** [comment]
thank you! will try
