### ISSUE TITLE
failing to run the initial example

### ISSUE THREAD

**Issue by deniskristak** [theislab/scib-pipeline#53]
Hi,
I've been trying to build this package from source. 
Because this is part of work on [Easybuild HPC package manager](https://easybuilders.github.io/) I am also taking care of dependencies manually, not using `conda`.

I'm using tag `0.2.0`.

It seems to install fine, but currently, when I try to run the initial example `snakemake -n --cores 1 --configfile config.yaml`,
I am getting this error:
```
Building DAG of jobs...
MissingInputException in rule integration_prepare in file /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/haswell-ib/software/scib-pipeline/0.2.0-foss-2022a/pipeline/Snakefile, line 32:
Missing input files for rule integration_prepare:
    output: /storage/groups/ml01/workspace/scIB/pancreas/prepare/unscaled/hvg/adata_pre.h5ad
    wildcards: scenario=pancreas, scaling=unscaled, hvg=hvg, prep=h5ad
    affected files:
        /storage/groups/ml01/workspace/maren.buettner/data_integration/data/human_pancreas/human_pancreas_norm.h5ad
```
Does it ring any bells? 
Thank you very much.

**Comment by LuckyMD** [comment]
Hi @deniskristak, it sounds like you need to adapt the config file you are using to point this towards the data you want to run this with.

**Comment by deniskristak** [comment]
Hi @LuckyMD,
thanks for catching up with me so early. Can you point me to where I could find the data you're talking about?
I honestly don't really know what kind of data the software is working with... I am only trying to run some sort of initial example according to the documentation, so that I know it's not throwing any errors or anything and that it installs all right.
Thanks!

**Comment by mumichae** [comment]
Hi, for a test datasets just for implementation testing I'd recommend you check out the [data directory](https://github.com/theislab/scib-pipeline/tree/main/data) of the repo. There should be a script that you can use to generate the test data as described [here](https://github.com/theislab/scib-pipeline#running-the-pipeline). You need to add the real path of the generated object to the config file for the pipeline to work.

**Comment by deniskristak** [comment]
this did help me progress, thanks! turns out I was using the latest official release you guys have (maybe think about adding next one? )
