### ISSUE TITLE
confuse in adata and adata_int

### ISSUE THREAD

**Issue by huawen-poppy** [theislab/scib-pipeline#57]
Hello! I am following the scib's tutorial https://scib.readthedocs.io/en/latest/api.html  
But there are some places i am not sure:

> scib.metrics.metrics(adata, adata_int, ari=True, nmi=True)

does the adata hear mean the object before integration, and adata_int mean the object after integration? For the object before integration, how can I generate it from two files? For example, I have A and B two raw data. Should I merge them to be the object before integration? and then perform the preprocess? Or should I perform the preprocess separately and then merge them?

**Comment by LuckyMD** [comment]
Hi @huawen-poppy,

You interpreted `adata` and `adata_int` correctly. You can join two datasets using scanpy's concatenate function. Something like `adata = adata1.concat(adata2, label='batch')`. You can see how this works [here](https://anndata.readthedocs.io/en/latest/concatenation.html). In general, it's best to normalize the unintegrated data together and call HVGs there. QC is best done per dataset or even per sample.
