### ISSUE TITLE
Benchmarking out of repo model integration metrics

### ISSUE THREAD

**Issue by jdenhof** [theislab/scib-pipeline#65]
I am working on integration models and wanted to test my models integration metrics against those currently supported in the pipeline. I was wondering if there is a way to run benchmarking on custom models? Is this currently supported?

**Comment by LuckyMD** [comment]
Hi @jdenhof,

Maybe the best place to do this is in our openproblems repository. Most of the scib-pipeline has been implemented in open problems now. You can find more information at www.openproblems.bio and on github at www.github.com/openproblems-bio/openproblems.

Hope this helps!

**Comment by Nowam** [comment]
@LuckyMD Might be worth adding this info to the README to help redirect users to the more maintained code, would've saved me a few hours :)
