### ISSUE TITLE
Issue with the pipeline

### ISSUE THREAD

**Issue by szhang99-bu** [theislab/scib-pipeline#9]
I am currently all set up according to the instruction, then should I run Snakemake in the base environment or scib-python?
However in either environment, when I am running the pipeline for either my own data or the test data, a syntax error occurs:

SyntaxError:
Input and output files have to be specified as strings or list of strings/
xxxxxx/xxxxx/xxxxxx/ scib-pipeline/Snakefile, line 10, in module
xxxxxx/xxxxx/xxxxxx/ scib-pipeline/scripts/preprocessing/Snakefile, line 23, in module

**Comment by szhang99-bu** [comment]
Here is my config.yaml file:
I've only changed the batch key and label key name to correlate with my own data.

ROOT: data
r_env : scIB-R-integration
py_env : scIB-python

timing: false
unintegrated_metrics: false

FEATURE_SELECTION:
  #hvg: 2000
  full_feature: 0

SCALING:
  - unscaled
  #- scaled

METHODS:
# python methods
  bbknn:
    output_type: knn
  combat:
    output_type: full
  #desc:
  #  output_type: embed
  mnn:
    output_type: full
  #saucie:
  #  output_type:
  #    - full
  #    - embed
  scanorama:
    output_type:
      - embed
      - full
  scanvi:
    output_type: embed
    no_scale: true
    use_celltype: true
  scgen:
    output_type: full
    use_celltype: true
  scvi:
    no_scale: true
    output_type: embed
  #trvae:
  #  no_scale: true
  # output_type:
  #    - embed
  #    - full
  # trvaep:
  #   no_scale: true
  #   output_type:
  #     - embed
  #     - full
# R methods
  #conos: # temporary directory issue
  #  R: true
  #  output_type: knn
  fastmnn:
    R: true
    output_type:
      - embed
      - full
  harmony:
    R: true
    output_type: embed
  liger:
    no_scale: true
    R: true
    output_type: embed
  seurat:
    R: true
    output_type: full
  seuratrpca:
      R: true
      output_type: full

DATA_SCENARIOS:
  test_data:
    batch_key: group
    label_key: Treat
    organism: mouse
    assay: expression
    file: data/mgc.h5ad

**Comment by LuckyMD** [comment]
Could you put the full file path into `file:` that goes from root? I'm curious if this might change something. Otherwise, any ideas @mumichae ?

**Comment by mumichae** [comment]
This should be working with relative paths, at least it was for me. Could repost your config in code notation i.e. ussing ``` before and after the file contents? That way we can see whether the formatting could be the problem

**Comment by szhang99-bu** [comment]
Also, should we installed the Seurat and scran packages via Bioconda or using BiocMananger inside the R environment. Since I was not able to successfully install anything via BiocManager

**Comment by mumichae** [comment]
I know R installation is a bit annoying, especially with the R version in the env being fixed at 3.6. I'm currently trying to get PR #6 merged, which should make pipeline setup much easier and has an install script for most R packages. Feel free to check out that branch https://github.com/theislab/scib-pipeline/tree/update_scanpy and let me know whether that solves some of your problems

**Comment by szhang99-bu** [comment]
Hi mumichae! 
So I've been using the new pipeline and it certainly has been much more easier compare to before! Thanks for all the changes. However, it seems that the Rscript has some error in it. Were you able to install all the packages using the Rscript?
`Skipping 3 packages not available: multtest, rsvd, SDMTools
Installing 117 packages: ape, askpass, BH, bitops, caTools, cli, cluster, colorspace, conquer, cowplot, cpp11, crayon, crosstalk, curl, data.table, digest, dplyr, dqrng, ellipsis, fansi, farver, fitdistrplus, FNN, future, future.apply, generics, ggplot2, ggrepel, ggridges, globals, glue, gplots, gridExtra, gtools, htmltools, htmlwidgets, httr, ica, igraph, irlba, isoband, jsonlite, labeling, later, lattice, leiden, lifecycle, listenv, lmtest, magrittr, MASS, mathjaxr, Matrix, MatrixModels, matrixStats, metap, mgcv, mime, mnormt, multcomp, multtest, mutoss, mvtnorm, nlme, numDeriv, openssl, parallelly, pbapply, pillar, pkgconfig, plotly, plotrix, plyr, png, promises, purrr, quantreg, R6, RANN, rappdirs, rbibutils, RcppAnnoy, RcppArmadillo, RcppEigen, RcppProgress, Rdpack, reshape2, reticulate, rlang, ROCR, RSpectra, rsvd, Rtsne, sandwich, scales, sctransform, SDMTools, sitmo, sn, SparseM, stringi, survival, sys, TFisher, TH.data, tibble, tidyr, tidyselect, tmvnsim, tsne, utf8, uwot, vctrs, viridisLite, withr, yaml, zoo
Error: (converted from warning) packages ‘multtest’, ‘rsvd’, ‘SDMTools’ are not available (for R version 3.6.1)
Execution halted
`

**Comment by LuckyMD** [comment]
Hi @szhang99-bu,
It seems that you might be on windows where R 4.0 is not yet available. I think we don't have an installscript specifically for `R<4.0` at the moment. Could you check if that's easy to adapt @mumichae ? Otherwise you might need to wait for MRO to support version 4.0.

**Comment by mumichae** [comment]
Sorry for the late reply, I hope this answer will help.
So far the pipeline has only been tested on R 3.6, and with time problems arise when installing via R. Installing the conda version of the missing packages usually did the trick for me. Also all the `update_scanpy` changes should be in the main branch by now

**Comment by mumichae** [comment]
Hi @szhang99-bu,
are you still facing issues with the environments or has it been resolved?
